<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="insert_robot" params="prefix">

        <xacro:property name="wheel_radius" value="0.169"/>
        <xacro:property name="wheel_seperation" value="0.4"/>

        <link name="${prefix}base_footprint"/>
        <link name="${prefix}base_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://former_description/meshes/visual/base_link.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://former_description/meshes/collision/base_link.stl" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.000 0.000 0.096" rpy="0 0 0"/>
                <mass value="32.571233"/>
                <inertia ixx="0.639569" ixy="0.000014" ixz="0.000423" iyy="0.635798" iyz="0.000003" izz="0.798308"/>
            </inertial>
        </link>

        <joint name="${prefix}base_link_fixed_joint" type="fixed">
            <parent link="${prefix}base_footprint"/>
            <child link="${prefix}base_link"/>
            <origin xyz="0 0 ${wheel_radius/2}" rpy="0 0 0"/>
        </joint>

        <xacro:macro name="insert_wheel" params="parent prefix dir">

            <link name="${prefix}_wheel_suspension">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 ${-dir*pi/2}"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/main_wheel_suspension.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 ${-dir*pi/2}"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/collision/main_wheel_suspension.stl" scale="1 1 1"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0.000 ${dir*0.026} 0.003" rpy="0 0 0"/>
                    <mass value="0.068691"/>
                    <inertia ixx="0.000014" ixy="0.000000" ixz="0.000000" iyy="0.000054" iyz="0.000000" izz="0.000061"/>
                </inertial>
            </link>

            <joint name="${prefix}_wheel_suspension_joint" type="fixed">
                <parent link="${parent}" />
                <child link="${prefix}_wheel_suspension" />
                <!-- <axis xyz="0 0 1"/> -->
                <origin xyz="0 ${dir*0.0741} 0" rpy="0 0 0"/>
                <!-- <limit effort="10" velocity="0.1" lower="-0.01" upper="0.01"/> -->
            </joint>

            <link name="${prefix}_wheel_mount">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 ${dir*pi/2}"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/main_wheel_mount.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 ${dir*pi/2}"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/collision/main_wheel_mount.stl" scale="1 1 1"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0.000 ${dir*0.026} 0.000" rpy="0 0 0"/>
                    <mass value="0.07885"/>
                    <inertia ixx="0.000002" ixy="0.000000" ixz="0.000000" iyy="0.0000003" iyz="0.000000" izz="0.000002"/>
                </inertial>
            </link>

            <joint name="${prefix}_wheel_mount_fixed" type="fixed">
                <parent link="${prefix}_wheel_suspension"/>
                <child link="${prefix}_wheel_mount"/>
                <origin xyz="0 ${dir*-0.003} 0" rpy="0 0 0"/>
            </joint>

            <link name="${prefix}_wheel">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 ${dir*pi/2}"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/main_wheel.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 ${dir*pi/2}"/>
                    <geometry>
                        <!-- <mesh filename="package://former_description/meshes/collision/main_wheel.stl" scale="1 1 1"/> -->
                        <sphere radius="0.0845"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="${dir*0.031} 0.000 0.000" rpy="0 0 0"/>
                    <mass value="0.843041"/>
                    <!-- <inertia ixx="0.002632" ixy="0.000000" ixz="0.000000" iyy="0.001536" iyz="0.000000" izz="0.001536"/> -->
                    <inertia ixx="0.1" ixy="0.0" ixz="0.0" iyy="0.1" iyz="0.0" izz="0.1"/>
                </inertial>
            </link>

            <joint name="${prefix}_wheel_joint" type="continuous">
                <parent link="${prefix}_wheel_mount"/>
                <child link="${prefix}_wheel"/>
                <axis xyz="0 1 0"/>
                <origin xyz="0 ${dir*0.051} 0" rpy="0 0 0"/>
                <dynamics damping="0.2"/>
            </joint>
        </xacro:macro>

        <xacro:insert_wheel parent="${prefix}base_link" prefix="${prefix}l" dir="1" />
        <xacro:insert_wheel parent="${prefix}base_link" prefix="${prefix}r" dir="-1" />


        <xacro:macro name="insert_front_caster_wheel" params="parent prefix1 prefix2 dir offset_x offset_y">
            <link name="${prefix1}_${prefix2}_caster_mount">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/caster_mount.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/collision/caster_mount.stl" scale="1 1 1"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0.000 0.000 -0.004" rpy="0 0 0"/>
                    <mass value="0.019629"/>
                    <inertia ixx="0.000006" ixy="0.000000" ixz="0.000000" iyy="0.000005" iyz="0.000000" izz="0.000010"/>
                </inertial>
            </link>

            <joint name="${prefix1}_${prefix2}_caster_mount_fixed_joint" type="fixed">
                <parent link="${parent}"/>
                <child link="${prefix1}_${prefix2}_caster_mount"/>
                <origin xyz="${offset_x} ${dir*offset_y} -0.0015" rpy="0 0 0"/>
            </joint>

            <link name="${prefix1}_${prefix2}_caster_rotate">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/caster_rotate.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/collision/caster_rotate.stl" scale="1 1 1"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="-0.012 0.000 -0.021" rpy="0 0 0"/>
                    <mass value="0.060591"/>
                    <inertia ixx="0.000020" ixy="0.000000" ixz="-0.000004" iyy="0.000022" iyz="0.000000" izz="0.000020"/>
                </inertial>
            </link>

            <joint name="${prefix1}_${prefix2}_caster_rotate_joint" type="continuous">
                <parent link="${prefix1}_${prefix2}_caster_mount"/>
                <child link="${prefix1}_${prefix2}_caster_rotate"/>
                <axis xyz="0 0 1"/>
                <origin xyz="0 0 -0.010" rpy="0 0 0"/>
            </joint>

            <link name="${prefix1}_${prefix2}_caster_wheel">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/caster_wheel.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/collision/caster_wheel.stl" scale="1 1 1"/>
                        <!-- <cylinder radius="0.0375" length="0.023"/> -->
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0.000 0.000 0.000" rpy="0 0 0"/>
                    <mass value="0.051842"/>
                    <!-- <xacro:cylinder_inertia m="0.032222" r="0.0375" h="0.023"/> -->
                    <inertia ixx="0.000013" ixy="0.000000" ixz="0.000000" iyy="0.000021" iyz="0.000000" izz="0.000013"/>
                </inertial>
            </link>

            <joint name="${prefix1}_${prefix2}_caster_wheel_joint" type="continuous">
                <parent link="${prefix1}_${prefix2}_caster_rotate"/>
                <child link="${prefix1}_${prefix2}_caster_wheel"/>
                <axis xyz="0 1 0"/>
                <origin xyz="-0.0235 0 -0.0415" rpy="0 0 0"/>
            </joint>
        </xacro:macro>

        <xacro:insert_front_caster_wheel parent="${prefix}base_link" prefix1="${prefix}f" prefix2="l" dir="1" offset_x="0.125" offset_y="0.087"/>
        <xacro:insert_front_caster_wheel parent="${prefix}base_link" prefix1="${prefix}f" prefix2="r" dir="-1" offset_x="0.125" offset_y="0.087"/>
        <xacro:insert_front_caster_wheel parent="${prefix}base_link" prefix1="${prefix}r" prefix2="l" dir="1" offset_x="-0.128" offset_y="0.099"/>
        <xacro:insert_front_caster_wheel parent="${prefix}base_link" prefix1="${prefix}r" prefix2="r" dir="-1" offset_x="-0.128" offset_y="0.099"/>

        <link name="${prefix}imu_sensor">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://former_description/meshes/visual/imu.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://former_description/meshes/collision/imu.stl" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0.0 0.0 0.0045" rpy="0 0 0"/>
                <mass value="0.1"/>
                <xacro:box_inertia m="0.032" x="0.032" y="0.032" z="0.009"/>
            </inertial>
        </link>

        <joint name="${prefix}imu_sensor_fixed_joint" type="fixed">
            <parent link="${prefix}base_link"/>
            <child link="${prefix}imu_sensor"/>
            <origin xyz="0.134 0 0.0045" rpy="0 0 0"/>
        </joint>

        <link name="${prefix}imu_link"/>

        <joint name="${prefix}imu_link_fixed_joint" type="fixed">
            <parent link="${prefix}imu_sensor"/>
            <child link="${prefix}imu_link"/>
            <origin xyz="0.0 0.0 0.009"/>
        </joint>

        <xacro:macro name="insert_sonar_sensor" params="parent prefix dir">
            <link name="${prefix}_sonar_sensor">
                <visual>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/visual/sonar_sensor.dae" scale="1 1 1"/>
                    </geometry>
                </visual>
                <collision>
                    <origin xyz="0 0 0" rpy="0 0 0"/>
                    <geometry>
                        <mesh filename="package://former_description/meshes/collision/sonar_sensor.stl" scale="1 1 1"/>
                    </geometry>
                </collision>
                <inertial>
                    <origin xyz="0.004 0.002 0.000" rpy="0 0 0"/>
                    <mass value="0.009290"/>
                    <inertia ixx="0.000001" ixy="0.000000" ixz="0.000000" iyy="0.000001" iyz="0.000000" izz="0.000001"/>
                </inertial>
            </link>

            <joint name="${prefix}_sonar_sensor_fixed" type="fixed">
                <parent link="${parent}"/>
                <child link="${prefix}_sonar_sensor"/>
                <origin xyz="0.184 ${dir*0.0968} 0.084" rpy="0 0 0"/>
            </joint>
        </xacro:macro>

        <xacro:insert_sonar_sensor parent="${prefix}base_link" prefix="${prefix}l" dir="1" />
        <xacro:insert_sonar_sensor parent="${prefix}base_link" prefix="${prefix}r" dir="-1" />


        <link name="${prefix}lidar_mount">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://former_description/meshes/visual/sick_tim5_lidar.dae" scale="1 1 1"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <geometry>
                    <mesh filename="package://former_description/meshes/collision/sick_tim5_lidar.stl" scale="1 1 1"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="-0.002 0.000 0.036" rpy="0 0 0"/>
                <mass value="0.180090"/>
                <inertia ixx="0.000139" ixy="0.000000" ixz="0.000002" iyy="0.000129" iyz="0.000000" izz="0.000094"/>
            </inertial>
        </link>

        <joint name="${prefix}lidar_mount_fixed_joint" type="fixed">
            <parent link="${prefix}base_link"/>
            <child link="${prefix}lidar_mount"/>
            <origin xyz="0.160 0 0.2275" rpy="${pi} 0 0"/>
        </joint>

        <link name="${prefix}laser_link"/>

        <joint name="${prefix}laser_link_fixed_joint" type="fixed">
            <parent link="${prefix}lidar_mount"/>
            <child link="${prefix}laser_link"/>
            <origin xyz="0 0 0.060" rpy="0 0 0"/>
        </joint>

        <xacro:sensor_d435i parent="${prefix}base_link" name="${prefix}camera" use_nominal_extrinsics="false">
            <origin xyz="0.1777 0 0.06715" rpy="0 ${-15*pi/180} 0"/>
        </xacro:sensor_d435i>

        <!-- <link name="${prefix}camera_depth_frame"/>

        <joint name="${prefix}camera_depth_frame_fixed" type="fixed">
            <parent link="${prefix}camera_link"/>
            <child link="${prefix}camera_depth_frame"/>
            <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}"/>
        </joint> -->
    </xacro:macro>
</robot>